### ISSUE TITLE
[TASK][new contact dialog] adapt the new create contact template dialog

### ISSUE THREAD

**Issue by rezk2ll** [OpenPaaS-Suite/esn-frontend-contacts#107]
[STORY](https://app.zenhub.com/workspaces/ft---calendar--contacts-dev-5ff3db9704b1b3001295e51f/issues/openpaas-suite/esn-frontend-contacts/94)

### TODO:
* [x] adapt the currently existing template to match the newly designed one and display it in a modal
### template changes:
- the fields are still the same, only the icons are added, the order is changed and the add new value and remove value are changed
![image.png](https://images.zenhubusercontent.com/5fbfc93511d9942f4ba77c52/8269d06a-ca04-4c22-8afa-4898aa0ae308)  becomes ![image.png](https://images.zenhubusercontent.com/5fbfc93511d9942f4ba77c52/8ec3b489-55c6-4fc6-bb0c-5fa1e9bb259e)

![image.png](https://images.zenhubusercontent.com/5fbfc93511d9942f4ba77c52/6bde5757-ac58-472d-b378-5e01d3fef94c) becomes ![image.png](https://images.zenhubusercontent.com/5fbfc93511d9942f4ba77c52/43c31afa-32e9-429a-bf80-75b6095504b2)
- the edit profile picture field is moved next to the first name and is smaller
- some fields are hidden and can be shown with the more options button

- the general structure could be:

```html
.modal
  .modal-dialog
    .modal-content
      .modal-header
        title
        button.close
      .modal-body
          content <- this is adapted template
      .modal-footer.flex
          button <- more options button?
          button <- some save button
```
* [x] remove the contactCreationSubheader files ( ie src/linagora.esn.contact/app/contact/create/contact-create-subheader.pug etc...)
* [x] handle the save button ( maybe use the existing one?)

**Comment by asmaNode** [comment]
https://github.com/OpenPaaS-Suite/esn-frontend-contacts/pull/123
https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/pull/185
