### ISSUE TITLE
[TASK][new contact dialog] adapt or create the route state of the new contact dialog

### ISSUE THREAD

**Issue by rezk2ll** [OpenPaaS-Suite/esn-frontend-contacts#108]
[STORY](https://app.zenhub.com/workspaces/ft---calendar--contacts-dev-5ff3db9704b1b3001295e51f/issues/openpaas-suite/esn-frontend-contacts/94)

### TODO:
* [x] modify the existing route ( `contact.addressbooks.new` view `main@contact` ) or create a new state route ( ie `/:adressbookId/contact/new` )
* [x] inject the create contact component with the `$modal` into the scope when entering the state
* [x] hide the dialog when leaving the state
* [x] pass the previous state as params to the state
* [x] make sure that the new contact dialog can be accessed via a URL
* [x] make sure that when you click on the + button you go to the new contact state
    - you can use the ContactLocationHelper.new or update it or remove it ( depends on your choice )

**Comment by asmaNode** [comment]
PR :https://github.com/OpenPaaS-Suite/esn-frontend-contacts/pull/117/
