### ISSUE TITLE
[TASK][Edit an existing contact in a dialog] adapt or create the route state of the contact edit dialog

### ISSUE THREAD

**Issue by rezk2ll** [OpenPaaS-Suite/esn-frontend-contacts#110]
[STORY](https://app.zenhub.com/workspaces/ft---calendar--contacts-dev-5ff3db9704b1b3001295e51f/issues/openpaas-suite/esn-frontend-contacts/93)

### TODO:
* [ ] modify the existing state route `contact.addressbooks.edit` or create a new one  ( ie `/:addressbookId/contact/:contactId/edit` )
* [ ] inject the edit contact component with the `$modal` into the scope when entering the state
* [ ] hide the dialog when leaving the state
* [ ] pass the previous state as params to the state
* [ ] make sure that the edit contact dialog can be accessed via a URL
* [ ] make sure that when you click on the edit contact button in the [show contact dialog](https://app.zenhub.com/workspaces/ft---calendar--contacts-dev-5ff3db9704b1b3001295e51f/issues/openpaas-suite/esn-frontend-contacts/106) you go to the edit contact state
    - you can use the ContactLocationHelper.edit or update it or remove it ( depends on your choice )

NOTE: 

Similar to https://app.zenhub.com/workspace/o/openpaas-suite/esn-frontend-contacts/issues/105
